name       : libkcddb
version    : 19.12.1
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/libkcddb-19.12.1.tar.xz : 50c139aaa14a5f27b3818cec7ec6ede4b764d461b6547651b61e4edd295afe6f
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
