name       : libkcddb
version    : 23.04.1
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/libkcddb-23.04.1.tar.xz : 093afa1af67284e26e1f7df5f630d9c89d7d85f6234f218e91dcf72e9306e242
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - kcmutils-devel
    - kdoctools-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
