name       : libkcddb
version    : 18.04.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/libkcddb-18.04.3.tar.xz : 15588b9c2d54fb4d3d1beb2120210c80bfdc87f54514559d6df9147a9569675a
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
