name       : libkcddb
version    : 21.12.3
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/libkcddb-21.12.3.tar.xz : 62709f9ccd8463208b905a3b935be1ba80102c451728e9f5c77e83eaf4afc191
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - kdoctools-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
