name       : libkcddb
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/libkcddb-17.08.3.tar.xz : f0743bafd82383b24ba2a06fa2945dac3feea3be301ddeca30281eb4994a1a7a
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
