name       : libkcddb
version    : 18.08.2
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/libkcddb-18.08.2.tar.xz : a403ddab8b7a6666a3d83fd98e7068478a3287f144df35494b47f0a32783998d
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
