name       : libkcddb
version    : 19.12.3
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/libkcddb-19.12.3.tar.xz : 69cbaf03adba24c0cabf957ee4149c4fa86d403eb6b8a07f7f80eb17be49e892
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
