name       : libkcddb
version    : 21.12.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/libkcddb-21.12.0.tar.xz : cd6c05bfae0d9b0ba37e30a34a3e995492a82bb9d370ff68db85c39406c83762
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - kdoctools-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
