name       : libkcddb
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/libkcddb-17.08.1.tar.xz : ff743d48a57b4933a1779e43a68bdfe9eff5e468b7709b50a56d699f4f7d281a
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
