name       : libkcddb
version    : 22.04.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/libkcddb-22.04.0.tar.xz : ddc91cc5112c5a749fccf18bb9a6b169279f6d5658fed3b4d60646d9ccbb0775
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - kdoctools-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
