name       : libkcddb
version    : 18.12.2
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/libkcddb-18.12.2.tar.xz : 4eb3c60a099e905183a8e3a91d4c39cbd826c73c5312b3ea82f7d39bc5c17d32
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
