name       : libkcddb
version    : 22.04.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/libkcddb-22.04.3.tar.xz : c80b57a73bc17aa71fc559545e173ae9b0e2dd925bbaadeaf37629dc21ca45cb
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(libmusicbrainz5)
    - kdoctools-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
