name       : libkcddb
version    : 17.12.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/libkcddb-17.12.3.tar.xz : f10a4612506be8de2326dbba06105ba245695f3204b88d636bb80c8f56ff91e3
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : programming
optimize   : lto
summary    : KDE CDDB library
description: |
    KDE CDDB library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
